# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                   MODELS                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[models."gpt-4o-mini-2024-07-18"]
routing = ["openai"]

[models."gpt-4o-mini-2024-07-18".providers.openai]
type = "openai"
model_name = "gpt-4o-mini-2024-07-18"

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                 FUNCTIONS                                  │
# └────────────────────────────────────────────────────────────────────────────┘

[functions.extract_entities]
type = "json"
output_schema = "functions/extract_entities/output_schema.json"

[functions.extract_entities.variants.gpt4o_mini_initial_prompt]
type = "chat_completion"
model = "gpt-4o-mini-2024-07-18"
system_template = "functions/extract_entities/initial_prompt/system_template.minijinja"
json_mode = "strict"

# ┌────────────────────────────────────────────────────────────────────────────┐
# │                                  METRICS                                   │
# └────────────────────────────────────────────────────────────────────────────┘

[metrics.exact_match]
type = "boolean"
level = "inference"
optimize = "max"

[metrics.jaccard_similarity]
type = "float"
level = "inference"
optimize = "max"

[metrics.valid_json]
type = "boolean"
level = "inference"
optimize = "max"


[models."accounts/viraj-ebfe5a/models/e78631ef5fad43fbbec00203c1a55579"]
routing = [ "fireworks",]

[models."accounts/viraj-ebfe5a/models/e78631ef5fad43fbbec00203c1a55579".providers.fireworks]
type = "fireworks"
model_name = "accounts/viraj-ebfe5a/models/e78631ef5fad43fbbec00203c1a55579"

[functions.extract_entities.variants."accounts/viraj-ebfe5a/models/e78631ef5fad43fbbec00203c1a55579"]
type = "chat_completion"
weight = 1
model = "accounts/viraj-ebfe5a/models/e78631ef5fad43fbbec00203c1a55579"
system_template = "functions/extract_entities/initial_prompt/system_template.minijinja"
