[profile.default]
retries = { backoff = "fixed", count = 2, delay = "5s", jitter = true }
slow-timeout = { period = "10s", terminate-after = 3 }

[profile.ci]
retries = { backoff = "exponential", count = 4, delay = "5s", jitter = true, max-delay = "60s" }

[profile.unit]
retries = 0
slow-timeout = { period = "2s", terminate-after = 1 }

# Test groups to manage provider rate limits

[test-groups]
e2e-anthropic = { max-threads = 1 }  # converted from 50 RPM
e2e-aws-bedrock = { max-threads = 2 }
e2e-azure = { max-threads = 5 }
e2e-fireworks = { max-threads = 3 }
e2e-gcp-vertex = { max-threads = 5 }
e2e-google-ai-studio = { max-threads = 5 }
e2e-mistral = { max-threads = 3 }
e2e-openai = { max-threads = 5 }
e2e-together = { max-threads = 3 }
e2e-vllm = { max-threads = 10 }
e2e-xai = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::anthropic::)'
test-group = 'e2e-anthropic'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::aws_bedrock::)'
test-group = 'e2e-aws-bedrock'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::azure::)'
test-group = 'e2e-azure'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::fireworks::)'
test-group = 'e2e-fireworks'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::gcp_vertex::)'
test-group = 'e2e-gcp-vertex'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::google_ai_studio::)'
test-group = 'e2e-google-ai-studio'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::mistral::)'
test-group = 'e2e-mistral'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::openai::)'
test-group = 'e2e-openai'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::together::)'
test-group = 'e2e-together'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::vllm::)'
test-group = 'e2e-vllm'

[[profile.default.overrides]]
filter = 'binary(e2e) and test(providers::xai::)'
test-group = 'e2e-xai'
